name: test-reuse
on:
  workflow_dispatch:
    inputs:
      test_inputs_reuse:
        description: "paste values to test_reusable"
        required: true
        default: "from reuse test-reuse"
jobs:
  call-workflow-test-reusable:
    uses: ./.github/workflows/test_reusable.yml
    with:
      REGION: ${{ inputs.test_inputs_reuse }}
