name: "test-composit"
description: "test composit"
inputs:
  TEST_INPUTS:
    required: true
    description: "test inputs"

env:
  MY_SECRET: "${{ secrets.TEST_SECRET }}"
    
runs:
  using: "composite"
  steps:
    - name: Checkout pipelines
      uses: actions/checkout@v3

    - name: List working directory
      shell: bash
      run: ls

    - name: test_inputs
      shell: bash
      run: |
        echo ${{ inputs.TEST_INPUTS }}

    # - name: test-secret
    #   shell: bash
    #   run: |
    #     echo test-secret: ${{ secrets.TEST_SECRET }}
