name: "test-composit"
description: "test composit"
inputs:
  TEST_INPUTS:
    required: true
    description: "test inputs"
    
runs:
  using: "composite"
  steps:
    - name: Checkout pipelines
      uses: actions/checkout@v3

    - name: List working directory
      shell: bash
      run: ls
        
    - name: Set up environment variables
      run: |
        echo "TEST_SECRET=${{ secrets.TEST_SECRET }}" >> $GITHUB_ENV
      shell: bash

    - name: test_inputs
      shell: bash
      run: |
        echo ${{ inputs.TEST_INPUTS }}

    - name: test-secret
      shell: bash
      run: |
        echo "Secret value: $TEST_SECRET"
