name: "test-composit"
description: "test composit"
inputs:
  TEST_INPUTS:
    required: true
    description: "test inputs"
    
runs:
  using: "composite"
  steps:
    - name: Checkout pipelines
      uses: actions/checkout@v4
      with:
        ref: ${{ secrets.BRANCH }}

    - name: List working directory
      shell: bash
      run: ls

    - name: test_inputs
      shell: bash
      run: |
        echo ${{ inputs.TEST_INPUTS }}

    # - name: test secret
    #   shell: bash
    #   run: |
    #     secret: ${{ secrets.TEST_SECRET }}

