name: test_reusable
on:
  repository_dispatch:
    types: [my-custom-event]
  workflow_call:
    inputs:

      test_inputs:
        required: true
        type: string
        
      RUNS_ON:
        required: true
        type: string

jobs:
  test-job:
    name: test-job-name
    runs-on: ${{ inputs.RUNS_ON }}
    steps:

      - name: Set GITHUB_ENV
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: |
          echo "Action by repository_dispatch"

      - name: Set GITHUB_ENV
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "echo "Action by workflow_dispatch"

      - name: "Checkout pipelines"
        uses: actions/checkout@v3 

      - name: "Common Setup"
        uses: ./.github/actions/common-setup
        with:
          TEST_INPUTS: ${{ inputs.test_inputs }}
