name: _test_reuse
on:
  workflow_dispatch:
    inputs:
      test_inputs:
        description: test inputs 
        required: true
        default: "test inputs from reuse pipelines"
      run-on:
        description: version of run-on include 'ubuntu-20.04' 'ubuntu-22.04'
        required: true
        default: "['ubuntu-20.04', 'ubuntu-22.04']"


jobs:
  call-workflow-deploy-microservice:
    strategy:
      fail-fast: false
      matrix:
        run-on: ${{ (inputs.run-on && fromJSON(inputs.run-on)) || fromJSON('["ubuntu-20.04", "ubuntu-22.04"]')  }}
    uses: ./.github/workflows/test_reusable.yml
    with:
      RUNS_ON: ${{ matrix.run-on }}
      test_inputs: ${{ inputs.test_inputs }}

      
